### ISSUE TITLE
Stepping parse TypeError on ARM

### ISSUE THREAD

**Issue by cyberb** [workhorsy/py-cpuinfo#10]
Hi,

I have the following exception on arm (raspberry pi):
````
root@raspberrypi:~# python
Python 2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cpuinfo import cpuinfo
>>> info = cpuinfo.get_cpu_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/cpuinfo.py", line 1194, in get_cpu_info
    info = get_cpu_info_from_proc_cpuinfo()
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/cpuinfo.py", line 789, in get_cpu_info_from_proc_cpuinfo
    stepping = int(_get_field(output, 'stepping'))
TypeError: int() argument must be a string or a number, not 'NoneType'
````
````
root@raspberrypi:~# cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
Features        : swp half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0010
Serial          : 00000000be6d9ba0
````

Version: py-cpuinfo-0.1.2 (pip)

**Comment by jonhp** [comment]
Hi,
Any chance of progress here? I just ran into this problem on BBW. A fix would certainly be nice. Thanks.

**Comment by workhorsy** [comment]
I just committed a fix to main, that probably fixed the issue. I don't yet have access to an ARM machine to test this on. Can you test it @jonhp ?

**Comment by workhorsy** [comment]
See 570717f2ee8f52820caf8c1977154437b96c8f5e for details.

**Comment by jonhp** [comment]
I think I did this right...not sure...

>>> from cpuinfo import cpuinfo
>>> info=cpuinfo.get_cpu_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cpuinfo/cpuinfo.py", line 1202, in get_cpu_info
    info = get_cpu_info_from_proc_cpuinfo()
  File "cpuinfo/cpuinfo.py", line 798, in get_cpu_info_from_proc_cpuinfo
    model = int(_get_field(output, 'model') or '0')
ValueError: invalid literal for int() with base 10: 'ARMv7 Processor rev 2 (v7l)'

**Comment by workhorsy** [comment]
Does it work now @jonhp ?
The main problem now is getting the CPU speed. Does your PI have the "vcgencmd" command?

**Comment by jonhp** [comment]
whoops. I should have noted earlier that I am running on a beaglebone white rev a6; not a pi. it does not have the "vcgencmd" command.

**Comment by workhorsy** [comment]
That's okay. Does the BeagleBone have "cpufreq-info" ? If so, can you show me the output of that command?

**Comment by jonhp** [comment]
debian@beaglebone:/$ cpufreq-info
cpufrequtils 008: cpufreq-info (C) Dominik Brodowski 2004-2009
Report errors and bugs to cpufreq@vger.kernel.org, please.
analyzing CPU 0:
  driver: generic_cpu0
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency: 300 us.
  hardware limits: 300 MHz - 1000 MHz
  available frequency steps: 300 MHz, 600 MHz, 800 MHz, 1000 MHz
  available cpufreq governors: conservative, ondemand, userspace, powersave, performance
  current policy: frequency should be within 300 MHz and 1000 MHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency is 1000 MHz.
  cpufreq stats: 300 MHz:0.00%, 600 MHz:0.00%, 800 MHz:0.00%, 1000 MHz:100.00%
debian@beaglebone:/$

**Comment by workhorsy** [comment]
What does the main branch give you for output now?

```python
python cpuinfo/cpuinfo.py
```

**Comment by jonhp** [comment]
debian@beaglebone:~/Downloads/test2/py-cpuinfo-master$ python cpuinfo/cpuinfo.py 
Vendor ID: None
Brand: ARMv7 Processor rev 2 (v7l)
Hz Advertised: 0.0000 Hz
Hz Actual: 0.0000 Hz
Hz Advertised Raw: (0, 0)
Hz Actual Raw: (0, 0)
Arch: ARM_7
Bits: 32
Count: 1
Raw Arch String: armv7l
L2 Cache Size: None
L2 Cache Line Size: 0
L2 Cache Associativity: 0
Stepping: 0
Model: 0
Family: 0
Processor Type: 0
Extended Model: 0
Extended Family: 0
Flags: edsp, fastmult, half, neon, swp, thumb, thumbee, tls, vfp, vfpv3
debian@beaglebone:~/Downloads/test2/py-cpuinfo-master$

**Comment by workhorsy** [comment]
Thank you. Since this technically solves the problem originally reported. I'm going to close this bug. I will make another for making it work on a BeagleBoard, and Raspberry PI.

**Comment by jonhp** [comment]
Thanks. I await new fixes.
