### ISSUE TITLE
Proc Serial

### ISSUE THREAD

**Issue by Syed-Hussaini2** [workhorsy/py-cpuinfo#107]
#This is not an issue, just a request!!

Hello!! 
Could you please let me know a way, where I can also get the Processor's serial number?

I need to generate a PY script to get these details for asses management.

Thank You
Syed Hussaini
email: syed.hussaini11@outlook.com

**Comment by workhorsy** [comment]
Unfortunately I don't think there is a reliable way to get a CPU's serial number anymore. There used to be a way to do it using CPUID on old Pentium II/III CPUs, but I think it is disabled in modern bios/OS for security reasons.

https://en.wikipedia.org/wiki/CPUID#EAX.3D3:_Processor_Serial_Number
