### ISSUE TITLE
On non BeOS systems, calling sysinfo may open GUI program

### ISSUE THREAD

**Issue by johann-petrak** [workhorsy/py-cpuinfo#136]
When calling cpuinfo.get_cpu_info() this package seems to try to run the command `sysinfo -cpu` if it finds that such a command is available. This is not a default package on Ubuntu 18.04 but after installing the package sysinfo using `sudo apt install sysinfo`, there is a script called `/usr/bin/sysinfo`
This script invokes a mono program `mono Sysinfo.exe` which seems to ignore all command line arguments. 
The GUI shows the following about information:
"Sysinfo 0.7 Copyright Nil Gradisnik 2006 <ghaefb@gmail.com>"
http://sourceforge.net/projects/gsysinfo

Since this GUI program is invoked, the call to `get_cpu_info()` hangs until the GUI is terminated.
Since this package is used in a number of other tools and packages, this is a real problem on systems where the "sysinfo" package is installed.

* CPU architecture x86_64
* Operating System Ubuntu 18.04
* Python version 3.6.8
* Version of py-cpuinfo 5.0.0

**Comment by workhorsy** [comment]
I'll add a check that only runs sysinfo on BeOS/Haiku.

**Comment by workhorsy** [comment]
Should be fixed now. Thanks.
