### ISSUE TITLE
The get_cache function has swapped fields

### ISSUE THREAD

**Issue by Lib95** [workhorsy/py-cpuinfo#140]
https://github.com/workhorsy/py-cpuinfo/blob/63931cb6b6b13b23b8ea5def60c5560cf7af6856/cpuinfo/cpuinfo.py#L1213-L1217 

The wikipedia source (https://en.wikipedia.org/wiki/CPUID#EAX=80000006h:_Extended_L2_Cache_Features) used for the function mentions the bits for the ECX register are line size (07-00), associativity (15-12), and then cache size (31-16), but the implementation has it ordered as cache size, line size, and then associativity.

**Comment by workhorsy** [comment]
I'll see if I can fix this. Thanks for your help.

**Comment by workhorsy** [comment]
Should be fixed now. Thanks.
