### ISSUE TITLE
CPU instruction "pext" as a flag?

### ISSUE THREAD

**Issue by PedanticHacker** [workhorsy/py-cpuinfo#153]
Using the latest version of `py-cpuinfo 7.0.0`, I didn't get the CPU instruction `pext` listed as a flag. Does the flag `pext` shows up if this instruction is present in the CPU? Anyone with a newer CPU, please check this.

**Comment by workhorsy** [comment]
As far as I can tell, it looks like PEXT is an instruction added with BMI2. So if you check the flags for ```"bmi2"``` the CPU should support PEXT.

```python

if __name__ == '__main__':
	from cpuinfo import get_cpu_info

	info = get_cpu_info()

	if 'bmi2' in info['flags']:
		print("CPU supports PEXT instruction")
	else:
		print("CPU does NOT support PEXT instruction")
```


https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#BMI2_(Bit_Manipulation_Instruction_Set_2)

**Comment by PedanticHacker** [comment]
Thanks very much for your answer! :)
