### ISSUE TITLE
CPUID(trace) API change in master is incompatible with 7.0.0

### ISSUE THREAD

**Issue by ftian1** [workhorsy/py-cpuinfo#158]
It's not bug report. I just want to mention an incompatible change in master.

with 7.0.0 release, user just need create a cpuid obj by cpuinfo.CPUID(). now master introduced a trace parameter in CPUID.__init__() but not set its default value to False. this way causes old code may crash in new release if you don't make the API backward compatibility. 

It's not a good user experience, suggest to add a default value for trace parameter.

# In your bug report please include:
* CPU architecture
IA
* Operating System
CentOS
* Python version
3.6.5
* Version of py-cpuinfo
7.0.0

**Comment by workhorsy** [comment]
Good idea. I should really make sure not to change the API. Even the internal one if necessary.

**Comment by workhorsy** [comment]
Fixed in c01626517b0b881e0af340867b983f01c326d317

**Comment by workhorsy** [comment]
Let me know if you have any other issues. Closing for now.

**Comment by ftian1** [comment]
@workhorsy  it's really great repo. 

one thing I would like to mention is it's better to keep CPUID class as one of user facing API and not  change it in future release. 

why I have such suggestion is in reality such repo is always behind the real h/w capability. 

for example, intel AVX512 VNNI is a new instruction set which old OS and your current repo couldn't detect without update. If CPUID class is always exposed as user facing API, we (user)  could send some asm intructions through CPUID class to detect rather than waiting for your repo updates.
