### ISSUE TITLE
Doesn't work with pyinstaller

### ISSUE THREAD

**Issue by kadnass-dz** [workhorsy/py-cpuinfo#168]
Doesn't work with pyinstaller can I know what the reason ?

**Comment by kadnass-dz** [comment]
**Sorry, I didn't see this**

# NOTE: Pyinstaller may spawn infinite processes if __main__ is not used
if __name__ == '__main__':
    from cpuinfo import get_cpu_info
    from multiprocessing import freeze_support

    # NOTE: Pyinstaller also requires freeze_support
    freeze_support()
    info = get_cpu_info()
    print(info)

**Comment by workhorsy** [comment]
Did it work for you?

**Comment by workhorsy** [comment]
I'm closing this bug for now. It seems that you have resolved the issue yourself. Feel free to re open it, if you have any more problems. Thanks.
