### ISSUE TITLE
The module not working correctly when compiling using pyinstaller or Cx_freeze

### ISSUE THREAD

**Issue by mouadessalim** [workhorsy/py-cpuinfo#174]
So basicly i am tring to compile a simple module (py-cpuinfo) with pyinstaller or Cx_freeze with the same issue. It compile correctly but when launching the process, it create a lot of it until my cpu is full.

```
#testcpu.py
from cpuinfo import get_cpu_info
print(get_cpu_info())
```
[![My cpu usage after launching the program][1]][1]

The weird thing about it is that it's perfecty working in developement mode (python code)
[![When launching with python][2]][2]
When compiling i am using this parameters : `pyinstaller --noconfirm --onedir --console  "C:/Users/Mouad/Desktop/Payloads/cookies-grabber/testcpu.py"`

Does someone know how to fix this issue ?
My CPU: AMD Ryzen 5 2600X 
Python version: Python 3.9
I am using Windows 10
py-cpuinfo version: 8.0.0

  [1]: https://i.stack.imgur.com/zp468.png
  [2]: https://i.stack.imgur.com/s23EW.png

**Comment by EaxMov** [comment]
yes, me too

**Comment by mouadessalim** [comment]
This is exactly what i am looking for !
Thanks.
