### ISSUE TITLE
Releasing a new version past 8.0.0

### ISSUE THREAD

**Issue by TalAmuyal** [workhorsy/py-cpuinfo#184]
So There are a few new commits since the last release.
Specifically, I'm waiting for having a wheel for the new version.
Can a new release be made?

If it won't be done soon, can a plan/reason be shared?

Thanks :)

**Comment by workhorsy** [comment]
I think it is almost ready for the next release. I just need to run a few more tests. Should be a few more days.

**Comment by TalAmuyal** [comment]
🚀
