### ISSUE TITLE
System exit called if CPU is not supported

### ISSUE THREAD

**Issue by nicolargo** [workhorsy/py-cpuinfo#27]
Hi,

i use py-cpuinfo in the Glances project (https://github.com/nicolargo/glances). On Raspberry Pi, if the CPU is not supported, Py-Cpuinfo call an (ugly) sys.exit(0) (https://github.com/workhorsy/py-cpuinfo/blob/master/cpuinfo/cpuinfo.py#L1478). It should be more "Pythonific" to raise an error.

Thanks in advance for the enhancement.

**Comment by workhorsy** [comment]
I'll look into it. Thanks.

**Comment by workhorsy** [comment]
Hey @krmnn, can you run the https://raw.githubusercontent.com/workhorsy/py-cpuinfo/master/tools/get_system_info.py script on your Raspberry Pi, and attach the output of the "system_info.txt" file please?

**Comment by krmnn** [comment]
Here you go:
[system_info.txt](https://github.com/workhorsy/py-cpuinfo/files/60650/system_info.txt)

**Comment by workhorsy** [comment]
Thanks

**Comment by workhorsy** [comment]
The code in main should fix the problem now. I'll need to test it on a few more systems to make sure though.

**Comment by workhorsy** [comment]
Fixed in commit 3b8cf63596f66afe50910c82f3f5d8b3e8e78fc4. Tested on Windows, Linux, BSD, Haiku, and OS X.
