### ISSUE TITLE
Missing AVX2 CPU flag on OS X

### ISSUE THREAD

**Issue by alimanfoo** [workhorsy/py-cpuinfo#29]
Apologies for the naive question, but will this package detect support for AVX2 instructions?

**Comment by workhorsy** [comment]
It might.

In most places it just wraps the OS tool for getting the cpu flags. So it does not look for specific cpu flags, but passes on the list that it receives. Each tool names cpu flags differently. In the case of querying the CPUID register directly with:
```
from cpuinfo import cpuinfo
cpuinfo.get_cpu_info_from_cpuid()
```
It should check for the AVX2 flag. I would recommend trying a few of the different functions and seeing the results.

**Comment by workhorsy** [comment]
Hmmm. Upon closer inspection, it seems that the get_cpu_info_from_cpuid() function is not checking for AVX2. I'll have to look at this later. It has been a long time since I wrote this assembly code.

I think this whole section is missing:
https://en.wikipedia.org/wiki/CPUID#EAX.3D7.2C_ECX.3D0:_Extended_Features

**Comment by alimanfoo** [comment]
Thanks a lot. I have a Python package which includes some C extensions, and
I need to detect AVX2 in order to decide which extensions to build.
Detection needs to work on Linux or Windows. If I can do this without cpuid
then that would be fine, although I guess using cpuid is the most direct
way to check.

On Friday, 15 January 2016, Matthew Brennan Jones <notifications@github.com>
wrote:

> Hmmm. Upon closer inspection, it seems that the get_cpu_info_from_cpuid()
> function is not checking for AVX2. I'll have to look at this later. It has
> been a long time since I wrote this assembly code.
>
> I think this whole section is missing:
> https://en.wikipedia.org/wiki/CPUID#EAX.3D7.2C_ECX.3D0:_Extended_Features
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/workhorsy/py-cpuinfo/issues/29#issuecomment-171846480>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by fnino** [comment]
Ran into the same issue; it is quite easy to solve in MacOS.  You should merge info from 
 sysctl's machdep.cpu.features and machdep.cpu.leaf7_features

**Comment by workhorsy** [comment]
I'm pretty sure this was incidentally fixed on another bug fix. Can anyone confirm that this works for them?

**Comment by fnino** [comment]
Yes, bug was fixed. Works fine in macos 10.12.4

**Comment by fnino** [comment]
great job, thanks !

**Comment by workhorsy** [comment]
This should be working now. Re-open if you have any problems.
