### ISSUE TITLE
Broken on Odroid XU3 armhf ARM 32bit

### ISSUE THREAD

**Issue by rsuzano** [workhorsy/py-cpuinfo#41]
Hi,
As described at the README, I'm openning this issue with my system_info.txt.

The hardware is an Samsung Exynos5422 Cortex™-A15 2Ghz and Cortex™-A7 Octa core CPUs

[system_info.txt](https://github.com/workhorsy/py-cpuinfo/files/228265/system_info.txt)

root@odroidHTPC:~/py-cpuinfo# python cpuinfo/cpuinfo.py
Traceback (most recent call last):
  File "cpuinfo/cpuinfo.py", line 1563, in <module>
    main()
  File "cpuinfo/cpuinfo.py", line 1531, in main
    info = get_cpu_info()
  File "cpuinfo/cpuinfo.py", line 1514, in get_cpu_info
    info = get_cpu_info_from_cpuid()
  File "cpuinfo/cpuinfo.py", line 935, in get_cpu_info_from_cpuid
    info = b64_to_obj(output)
  File "cpuinfo/cpuinfo.py", line 177, in b64_to_obj
    b = pickle.loads(a)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '6'

**Comment by workhorsy** [comment]
Thanks for the bug report. I will soon try to get it working on Android. This will help.

**Comment by rsuzano** [comment]
workhorsy, just to know, it's an ARM CPU but the O.S. is ubuntu 15.10 armhf 32bits.

Its a Single board computer made by HardKernel called Odroid XU4, based on Samsung exynios octa core SoC

**Comment by workhorsy** [comment]
Oh. I guess I should not have assumed that ARM means Android. I will have to find a way to test Ubuntu on an ARM cpu.

**Comment by workhorsy** [comment]
@rsuzano can you tell me if the new 3.0.0 release works?

**Comment by rsuzano** [comment]
@workhorsy  sorry, but I've decided to disassemble my XU4 cloudshell by heating issues....Now I put my XU4 in a 20cmx20cm Electrical Junction Box with heatsink in both sides of board and removed the LCD. Sorry....

**Comment by workhorsy** [comment]
That is okay. Maybe I'll be able to test it on the Odroid XU4 another way.
