### ISSUE TITLE
FreeBSD Segfaults with Python2/3

### ISSUE THREAD

**Issue by sparcdr** [workhorsy/py-cpuinfo#44]
I have written my own def for FreeBSD support as the standard `dmesg -a | grep Features` results in a segfault.

http://pastebin.com/nyjn38B8

Please incorporate this and add `info = get_cpu_info_from_freebsd()` just after the Windows block to fix the issue.  Thanks.

**Comment by sparcdr** [comment]
Output -
$ python info.py
Vendor ID: GenuineIntel
Brand: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Hz: 3.4000 GHz
Arch: X86_64
Bits: 64
Count: 8
RAW Hz: (3400000000, 0)
RAW Arch String: a, m, d, 6, 4
L2 Cache Size: 0
L2 Cache Line Size: 0
L2 Cache Associativity: 0
Stepping: 0
Model: 0
Family: 0
Processor Type: 0
Extended Model: 0
Extended Family: 0
Flags: acpi, apic, clflush, cmov, cx8, de, dts, fpu, fxsr, htt, mca, mce, mmx, msr, mtrr, pae, pat, pbe, pge, pse, pse36, sep, ss, sse, sse2, tm, tsc, vme

**Comment by workhorsy** [comment]
Thanks for the bug report.

It should already work on FreeBSD using the ```get_cpu_info_from_sysctl()``` function. This is probably a bug in the implementation. (I'm working on adding better documentation for the next release BTW).

Can you run the script ```tools/get_system_info.py``` and attach the output of the ```"system_info.txt"``` file please?

**Comment by sparcdr** [comment]
[system_info.txt](https://github.com/workhorsy/py-cpuinfo/files/237010/system_info.txt)

**Comment by sparcdr** [comment]
FreeBSD 10 uses a different sysctl oid than what your script was calling for it appears.  Here's the logical method I believe:

$ sysctl machdep.tsc_freq
machdep.tsc_freq: 3408168522

You will have to tweak the math because it complains that the int is "too directly base 10" or something even though I compared it to the raw hz length which my Windows machine output.  Most likely a spurious issue caused by the lack of rounding with the TSC (Time Stamp Counter) output.

**Comment by workhorsy** [comment]
Sorry. I'm confused here. What do you get when you run ```get_cpu_info_from_dmesg()```? Is there a stack trace? Will that work on BSD rather than ```get_cpu_info_from_sysctl()```?

**Comment by sparcdr** [comment]
Gives me "None".  Not because dmesg is not in the path as my regular user but more likely because FreeBSD doesn't output cpu into dmesg -a.  For that fact, it does not output any CPU information at all into dmesg.  The better fix IMHO would be to incorporate the small fixes into the sysctl function and detect the platform to avoid using the flags that are assumed.  This is what caused the crash in the first place so I determined.  On FreeBSD, you should grep the boot messages file instead.  Hope this helps.

`flags = run_and_get_stdout('grep Features= /var/run/dmesg.boot')`

**Comment by workhorsy** [comment]
@sparcdr can you tell me if the new 3.0.0 release works?

**Comment by workhorsy** [comment]
I'm pretty sure this bug was incidentally fixed in the 3.0.0 release. It is also an old bug. So If I don't get any feedback soon, I will close the bug.

**Comment by workhorsy** [comment]
Sorry accidentally close the wrong bug by mistake.

**Comment by workhorsy** [comment]
I'm closing this bug for now. If you still have this problem, feel free to re-open it, and provide more details.
