### ISSUE TITLE
conda package (on conda-forge)

### ISSUE THREAD

**Issue by mstimberg** [workhorsy/py-cpuinfo#48]
Since py-cpuinfo is a pure Python package, installation is of course not a big issue. However, some packages that have compiled C-extensions (like one of ours) might depend on it and those now often tend to provide conda packages to make installation easier. Only conda packages can be dependencies of conda packages, so that's why we created a conda package for py-cpuinfo on anaconda.org (https://anaconda.org/brian-team/py-cpuinfo) -- judging from the number of downloads, it's quite popular!
What do you think of having a package on conda-forge (http://conda-forge.github.io/) instead? I'd be happy to create the package recipe (again, for a pure Python package this is rather trivial) and I could list you and me as maintainers (or only you or only me if you prefer).

**Comment by workhorsy** [comment]
I'm not that familiar with anaconda or conda-forge. But feel free to add a package for py-cpuinfo on either site. Just please add a link to https://github.com/workhorsy/py-cpuinfo, so people know where upstream is. Feel free to list yourself as the recipe maintainer.

Thanks for the help.

**Comment by mstimberg** [comment]
I created a conda recipe and opened a pull request to include it in conda-forge (conda-forge/staged-recipes#2379). The package meta data contains the URL of this repository which will be displayed prominently in the "feedstock" github repository (which is responsible for building the actual package). Unfortunately, anaconda.org seems to not display this information for now...

**Comment by workhorsy** [comment]
Looks good. Hopefully Anaconda will get updated to show a description and other basic information.

Thanks.

**Comment by mstimberg** [comment]
The conda package is now up:
https://github.com/conda-forge/py-cpuinfo-feedstock
https://anaconda.org/conda-forge/py-cpuinfo

To install `py-cpuinfo` via conda, use
```
conda install -c conda-forge py-cpuinfo
```
