### ISSUE TITLE
Not working on OS X 10.12 Sierra

### ISSUE THREAD

**Issue by phreeza** [workhorsy/py-cpuinfo#59]
Not sure what may be causing this, and I didn't find any options for verbose output.

Calling `cpuinfo.get_cpu_info() ` returns `None` on my machine, 2011 MBA running OS X 10.12.3. Getting the info with `sysctl` seems to work fine on the command line.

Happy to provide any additional info that may help debug this.

**Comment by workhorsy** [comment]
Can you give me the file system_info.txt that is generated by this script?:
https://raw.githubusercontent.com/workhorsy/py-cpuinfo/master/tools/get_system_info.py

**Comment by workhorsy** [comment]
Also, what version of py-cpuinfo are you using?

**Comment by phreeza** [comment]
I am using py-cpuinfo==0.2.7 installed with pip.

Here is my 
[system_info.txt](https://github.com/workhorsy/py-cpuinfo/files/862064/system_info.txt)

**Comment by workhorsy** [comment]
Thanks

**Comment by workhorsy** [comment]
Looks like it was assuming `sysctl` would always have a `machdep.cpu.leaf7_features` field.
