### ISSUE TITLE
On Windows use win32 cpuid function instead of registry

### ISSUE THREAD

**Issue by workhorsy** [workhorsy/py-cpuinfo#6]
The Windows registry is missing newer flags like sse3, et cetera. See if we can use Python ctypes to call the win32 cpuid function instead.

**Comment by niklasf** [comment]
Unfortunately this seems to be a compiler builtin. So there is now standard DLL that could be loaded using ctypes.

**Comment by workhorsy** [comment]
@niklasf Do you know which API call? I remember looking for that before, but could not find it.

**Comment by niklasf** [comment]
Oh ... that was a bad typo, turning the meaning around. I wanted to say, that I don't think there is any standard shared library that exposes this.

The closest thing to using `__cpuid` I could find is https://github.com/flababah/cpuid.py. It allocates a block of executable memory to directly execute the CPUID processor instruction using ctypes. Actually pretty cool and also licensed MIT, so it could be added here.

I just [pr'ed](https://github.com/flababah/cpuid.py/pull/1) Python 3 support and a fix for Linux support to that project.

**Comment by workhorsy** [comment]
Hmm. I think we are talking about something different then. Apparently there is a compiler constant ```__cpuid``` that will do it at C++ compile time. But there is also a win32 API call that will work with ctypes. Something like:
```python
import ctypes
c = ctypes.windll.cpuid
print(c.GetCpuidEcx())
```

That is more what I am looking for. But I was never able to get it to work. I should have been more clear in this bug report.

**Comment by workhorsy** [comment]
@niklasf Also. py-cpuinfo can work by generating code dynamically to query the CPUID register just like the https://github.com/flababah/cpuid.py repo. It even works in Python 2 and 3. You just do:
```python
import cpuinfo
a = cpuinfo.get_cpu_info_from_proc_cpuinfo()
print(a)
```

I guess I need to update the documentation to make that more clear.

**Comment by niklasf** [comment]
Cool! That's awesome. I am not aware of any GetCpuidEcx API call or similar that comes with Windows.

**Comment by workhorsy** [comment]
It looks like I was wrong about there being a win32 api call. I'm closing this bug for now.
