### ISSUE TITLE
Not working on ARM64 odroid-c2

### ISSUE THREAD

**Issue by issamu2k** [workhorsy/py-cpuinfo#60]
Not currently supported on aarch64. 
I know it's duplicated here (https://github.com/workhorsy/py-cpuinfo/issues/49), but the other guy has not provided the system_info.
No much info is is available on this particular board, so I think it is just fixing cpufreq-info output parsing.

[system_info.txt](https://github.com/workhorsy/py-cpuinfo/files/888802/system_info.txt)

**Comment by workhorsy** [comment]
Thanks
