### ISSUE TITLE
Add s390x support

### ISSUE THREAD

**Issue by ngothan** [workhorsy/py-cpuinfo#69]
s390x is still not supported in the latest 3.2.0 version. I have created the first proposed patch which makes it working on s390x plattform.

It would be great if it could be reviewed and merged into upstream for next version.
Thanks

[py-cpuinfo-s390x.txt](https://github.com/workhorsy/py-cpuinfo/files/942978/py-cpuinfo-s390x.txt)

**Comment by pnemade** [comment]
and for writing test case for this s390x arch [here](https://pnemade.fedorapeople.org/py-cpuinfo.s390x.txt) is system info file.

**Comment by workhorsy** [comment]
Thank you. I'll see about adding it.

**Comment by workhorsy** [comment]
Hello @ngothan and @pnemade (or anyone with a s390x). Can either of you test the s390x branch and see if it works? https://github.com/workhorsy/py-cpuinfo/tree/s390x

These should be sufficient:

```
python cpuinfo/cpuinfo.py
```

```
python test_suite.py
```

**Comment by ngothan** [comment]
Hello Matthew,

sure, i will test it next week and give you the feedbacks.

Thank you!

Than


Am 25.01.2018 um 19:13 schrieb Matthew Brennan Jones:

**Comment by ydjainopensource** [comment]
Saw this issue in one of my google search results.

@workhorsy I tried running on s390x. Only some fields are displayed. I am attaching the full output

>cpuinfo version: (3, 3, 0)
Vendor ID: IBM/S390
Hardware Raw: 
Brand: 
Hz Advertised: 
Hz Actual: 
Hz Advertised Raw: 
Hz Actual Raw: 
Arch: S390X
Bits: 64
Count: 2
Raw Arch String: s390x
L1 Data Cache Size: 128 KB
L1 Instruction Cache Size: 96 KB
L2 Cache Size: 2048 KB
L2 Cache Line Size: 
L2 Cache Associativity: 
L3 Cache Size: 65536 KB
Stepping: 
Model: 
Family: 
Processor Type: 
Extended Model: 
Extended Family: 
Flags: dfp, eimm, esan3, etf3eh, highgprs, ldisp, msa, sie, stfle, vx, zarch

Do you want anything else?

If you want you can get access to an s390x instance by registering [here](https://linuxone20.cloud.marist.edu/cloud/#/register).
Once the 120 day trial is over, you can reapply. They usually approve all requests.

**Comment by workhorsy** [comment]
Thanks @ydjainopensource , I'll see if I can get it running on there.

**Comment by QuLogic** [comment]
I rebased that [branch](https://github.com/QuLogic/py-cpuinfo/tree/s390x), made a patched build of 5.0.0, and ran a [scratch build](https://koji.fedoraproject.org/koji/taskinfo?taskID=34608427). Anything that wasn't s390x failed because `test_linux_fedora_5_s390x` is run on all systems. On [s390x](https://kojipkgs.fedoraproject.org//work/tasks/8432/34608432/build.log) there are two failures:
```
======================================================================
FAIL: test_all (test_linux_fedora_5_s390x.TestLinuxFedora_5_s390x)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/py-cpuinfo-5.0.0/tests/test_linux_fedora_5_s390x.py", line 460, in test_all
    self.assertEqual('5.5040 GHz', info['hz_advertised'])
AssertionError: '5.5040 GHz' != '5.0000 GHz'
- 5.5040 GHz
?   - -
+ 5.0000 GHz
?     ++

======================================================================
FAIL: test_returns (test_linux_fedora_5_s390x.TestLinuxFedora_5_s390x)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/py-cpuinfo-5.0.0/tests/test_linux_fedora_5_s390x.py", line 399, in test_returns
    self.assertEqual(15, len(cpuinfo.get_cpu_info()))
AssertionError: 15 != 16
----------------------------------------------------------------------
```

**Comment by workhorsy** [comment]
Thanks for looking into this @QuLogic. I'm trying to jog my memory about this branch. It has been a year and a half.

I kept running into problems testing the branch, because I don't have access to a S390X machine. I tried to get it set up on https://linuxone20.cloud.marist.edu/ as @ydjainopensource recommended, but was not able to get enough free time to figure out the setup instructions.

The way the test suite is setup, it should run all the tests no matter what arch it is running on. I'm not sure why it failed. I just tested the branch on a X86_64 machine and it passes.

**Comment by workhorsy** [comment]
I'll have to look around and see if I can get this tested again. I should probably redo this branch too. It is based on py-cpuinfo version 3, which is super outdated.

**Comment by workhorsy** [comment]
Thanks. I'll see if I can try this out soon.

**Comment by workhorsy** [comment]
I just merged the branch. Let me know if it works

**Comment by ngothan** [comment]
it works perfectly :) thanks for merging

```
[root@devel3 py-cpuinfo]# python3 test_suite.py 
....................................................s.....................................................................................
----------------------------------------------------------------------
Ran 138 tests in 13.519s

OK (skipped=1)

[root@devel3 py-cpuinfo]# python3 cpuinfo/cpuinfo.py
Python Version: 3.7.2.final.0 (64 bit)
Cpuinfo Version: 5.0.0
Vendor ID Raw: IBM/S390
Hardware Raw: 
Brand Raw: 
Hz Advertised Friendly: 5.5040 GHz
Hz Actual Friendly: 5.5040 GHz
Hz Advertised: (5504000000, 0)
Hz Actual: (5504000000, 0)
Arch: S390X
Bits: 64
Count: 4
Arch String Raw: s390x
L1 Data Cache Size: 96 KB
L1 Instruction Cache Size: 64 KB
L2 Cache Size: 1024 KB
L2 Cache Line Size: 
L2 Cache Associativity: 
L3 Cache Size: 49152 KB
Stepping: 
Model: 
Family: 
Processor Type: 
Extended Model: 
Extended Family: 
Flags: dfp, edat, eimm, esan3, etf3eh, highgprs, ldisp, msa, sie, stfle, te, zarch
```
