### ISSUE TITLE
Does not run on appveyor CI infrastructure (Windows)

### ISSUE THREAD

**Issue by mstimberg** [workhorsy/py-cpuinfo#71]
`py-cpuinfo 3.2.0` seems to fail on the [appveyor CI](http://appveyor.com/) infrastructure (`Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs`), which is unfortunate because it prevents me from updating the conda packages on conda-forge (I can't really say whether this is a newly introduced problem in `py-cpuinfo`, though, it might also be due to changes in appveyor). This is a bit tricky to debug since I do not have direct access to their machines.
It fails both for 32bit and 64bit testing architectures, here's the `system_info.txt` output:
```
sys.executable:
===============================================================================
C:\Miniconda\python.exe
sys.version_info:
===============================================================================
sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
multiprocessing.cpu_count:
===============================================================================
2
platform.uname:
===============================================================================
('Windows', 'APPVYR-WIN', '2012ServerR2', '6.3.9600', 'AMD64', 'Intel64 Family 6 Model 63 Stepping 2, GenuineIntel')
platform.architecture:
===============================================================================
('32bit', 'WindowsPE')
platform.system:
===============================================================================
Windows
platform.machine:
===============================================================================
AMD64
```

(The only difference between 32bit and 64bit platforms is the first element of `platform.architecture`)

**Comment by workhorsy** [comment]
Interesting. I've never herd of AppVeyor. I'll look into to it, and see if I can figure out what is wrong.

**Comment by mstimberg** [comment]
Um, maybe wait a bit before spending time on this... I just figured out that it is not a general problem of appveyor, running `py-cpuinfo` directly there works, I got the error only during the `conda build` process (the installation works fine, but when it tries to run `import cpuinfo` as a test, the exception is raised). I'll get back to you, possibly I can reproduce it in a Windows VM.
Maybe as a small suggestion: it could be helpful for future debugging if the `_check_arch` function would state the `arch` it did not recognize in its error message. In my case here, it *should* be `AMD64` (translated to `x86_64`) but apparently it is not for some weird reason -- it would be nice to see the unrecognised value directly in the error message.

**Comment by mstimberg** [comment]
Sorry for the noise, this is definitely a regression in `conda-build`, I'll open an issue with them. What happens is that during the test phase of a conda package, functions like `platform.machine()` return `None` -- no wonder that importing `cpuinfo` fails in this situation.

**Comment by workhorsy** [comment]
That is okay. I'll have to work on a verbose mode, to make it easier to see what is happening when things fail.

**Comment by mstimberg** [comment]
Just as a follow-up in case you are curious (or for other that run into similar issues): the reason why `platform.machine()` returned `None` was that on Windows this function uses environment variables to figure out the information (in particular, it seems to use `PROCESSOR_ARCHITEW6432`, `PROCESSOR_ARCHITECTURE`, and `PROCESSOR_IDENTIFIER`). During the conda-build process, environment variables are not passed on from the surrounding environment by default, to avoid non-reproducible builds that depend on local environments. They have a system for explicitly "white-listing" environment variables, though, passing through the three mentioned variables makes the build work again.
