### ISSUE TITLE
Release & publish deb package

### ISSUE THREAD

**Issue by GianlucaBortoli** [workhorsy/py-cpuinfo#75]
If I'm not wrong, this module is not available via APT but only via PIP.
Is it possible to publish it in some PPA so that I can put it as a deb dependency?

**Comment by workhorsy** [comment]
As far as I know, no one has made a PPA/deb package for py-cpuinfo yet. I would love for someone to give it a try. Great idea!

**Comment by GianlucaBortoli** [comment]
I successfully created a deb package. When I've got some spare time, I'll create a PPA for it.
I'll keep you informed!

**Comment by GianlucaBortoli** [comment]
I just had some time to create a PPA and upload all the files. Now it's building and it should be fine soon.
Here's the link:

https://launchpad.net/~gianlucabortoli/+archive/ubuntu/py-cpuinfo

**Comment by GianlucaBortoli** [comment]
I just checked and the PPA looks good to me. Give it a try and let me know.

**Comment by workhorsy** [comment]
Sorry for the delays on this. I'm still working on getting this tested. I've had problems with my test VMs getting corrupt for some reason. I'll see if I can get this tested soon.

**Comment by GianlucaBortoli** [comment]
Don't worry, it's kind of a busy period for me too. Tell me if I can help you in some way.

**Comment by workhorsy** [comment]
I'm closing this bug now. As there are plenty of deb and rpm packages out there now.
