### ISSUE TITLE
not show infos about CPU 

### ISSUE THREAD

**Issue by catafest** [workhorsy/py-cpuinfo#86]
# In your bug report please include:
* CPU architecture: 
PS C:\WINDOWS\system32> Get-WmiObject Win32_Processor

Caption           : Intel64 Family 6 Model 60 Stepping 3
DeviceID          : CPU0
Manufacturer      : GenuineIntel
MaxClockSpeed     : 3201
Name              : Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
SocketDesignation : SOCKET 0

* Operating System:  Windows 10

* Python version: Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] on win32

* Version of py-cpuinfo : last update 

c:\Python27>python -m pip install -U py-cpuinfo
Requirement already up-to-date: py-cpuinfo in c:\python27\lib\site-packages

my output of c:\Python27>python -m cpuinfo

c:\Python27>python -m cpuinfo
cpuinfo version: (3, 3, 0)
Vendor ID: GenuineIntel
Hardware Raw:
Brand: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
Hz Advertised: 3.2000 GHz
Hz Actual: 3.1930 GHz
Hz Advertised Raw: (3200000000L, 0)
Hz Actual Raw: (3193000000L, 0)
Arch: X86_64
Bits: 64
Count: 4
Raw Arch String: AMD64
L2 Cache Size:
L2 Cache Line Size:
L2 Cache Associativity:
Stepping:
Model:
Family:
Processor Type:
Extended Model:
Extended Family:
Flags: 3dnow, acpi, clflush, cmov, de, dts, fxsr, ia64, mca, mce, mmx, msr, mtrr, pse, sep, serial, ss, sse, sse2, tm, tsc

**Comment by workhorsy** [comment]
I'll look into this. Thanks

**Comment by workhorsy** [comment]
Can you attache the "system_info.txt" generated by this script?
```
python tools/get_system_info.py
```

**Comment by workhorsy** [comment]
I'm closing this for now. Please re open if you have the info
